name: amazon_reviews
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - nltk
  - inflect
  - gensim
  - tensorflow
  - ipykernel  
  - tensorboard
  - langdetect
  - googletrans-3.1.0a0
  - unidecode
  - selenium
  - webdriver_manager
  - transformers



